Repository AY2324S2-CS2103T-W09-2/tp, pull requests merged in 2024-03, with the labels that each got.

#14 Update user stories in DG
  docs/DeveloperGuide.md
Labels: documentation

#22 docs: update website config file
  docs/_markbind/layouts/default.md
Labels: documentation

#25 feat: update list command
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement

#26 feat: Add single note to Startup
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#31 feat: update find command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/FundingStageContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/IndustryContainsKeywordsPredicate.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindByFundingStageCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByIndustryCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByNameCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement

#40 test: Test coverage for Note Command
  docs/UserGuide.md
  docs/images/tracing/NoteCommand.png
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/startup/Startup.java
  src/main/java/seedu/address/storage/JsonAdaptedStartup.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/testutil/EditStartupDescriptorBuilder.java
  src/test/java/seedu/address/testutil/NoteStartupDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StartupBuilder.java
Labels: enhancement

#43 Updated UG
  docs/UserGuide.md
Labels: documentation

#55 Branch addmarketval
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/startup/Startup.java
  src/main/java/seedu/address/model/startup/Valuation.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStartup.java
  src/main/java/seedu/address/ui/StartupCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/StartupListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStartupAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStartupAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStartupAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStartupAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStartupAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditStartupDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/startup/StartupTest.java
  src/test/java/seedu/address/model/startup/ValuationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStartupTest.java
  src/test/java/seedu/address/testutil/EditStartupDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StartupBuilder.java
  src/test/java/seedu/address/testutil/StartupUtil.java
  src/test/java/seedu/address/testutil/TypicalStartups.java
Labels: type.Story
